### ISSUE TITLE
Cannot iterate over null (null) for cloudmapper.py collect

### ISSUE THREAD

**Issue by tommy-bee** [duo-labs/cloudmapper#166]
When I run 
```
→$python cloudmapper.py collect --account my_account
```

I get a null reference error:
```
* Getting region names
* Creating directory for each region name
* Getting iam:generate-credential-report info
Making call for account-data/./my_account/us-east-1/iam-generate-credential-report.json
* Getting sts:get-caller-identity info
Making call for account-data/./my_account/us-east-1/sts-get-caller-identity.json
* Getting iam:get-account-authorization-details info
Making call for account-data/./my_account/us-east-1/iam-get-account-authorization-details.json
  ...paginating
  ...paginating
* Getting iam:get-account-password-policy info
Making call for account-data/./my_account/us-east-1/iam-get-account-password-policy.json
* Getting iam:get-account-summary info
Making call for account-data/./my_account/us-east-1/iam-get-account-summary.json
* Getting iam:list-account-aliases info
Making call for account-data/./my_account/us-east-1/iam-list-account-aliases.json
* Getting iam:get-credential-report info
Making call for account-data/./my_account/us-east-1/iam-get-credential-report.json
* Getting iam:list-saml-providers info
Making call for account-data/./my_account/us-east-1/iam-list-saml-providers.json
* Getting iam:get-saml-provider info
Traceback (most recent call last):
  File "cloudmapper.py", line 69, in <module>
    main()
  File "cloudmapper.py", line 64, in main
    commands[command].run(arguments)
  File "/Users/tommy/src/aws/cloudmapper/commands/collect.py", line 221, in run
    collect(args)
  File "/Users/tommy/src/aws/cloudmapper/commands/collect.py", line 183, in collect
    values = pyjq.all(pyjq_parse_string or "", parameter_values)
  File "/Users/tommy/src/aws/cloudmapper/venv/lib/python3.7/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)
(venv)
```

I add  these permission to the IAM user:
- `arn:aws:iam::aws:policy/SecurityAudit`
- `arn:aws:iam::aws:policy/job-function/ViewOnlyAccess`

Running on
mac high sierras

i did have to make these version updates to make it run on mac:
```
→$git diff requirements.txt
diff --git a/requirements.txt b/requirements.txt
index b9e268a..e7ffb5c 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,10 +1,10 @@
-pyjq==2.1.0
+pyjq==2.2.0
 netaddr==0.7.19
 six==1.10.0
 boto3==1.5.32
-pandas==0.22.0
+pandas==0.23.4
 matplotlib==2.2.2
 geoip2==2.8.0
 policyuniverse==1.1.0.1
-pyyaml==3.12
-pyproj==1.9.5.1
\ No newline at end of file
+pyyaml==3.13
+pyproj==1.9.5.1
```

**Comment by 0xdabbad00** [comment]
Looks like I need to work more on #164 to add more error handling, but also, it looks like I had swapped the saml provider collection and the open-id collection here: https://github.com/duo-labs/cloudmapper/blob/master/collect_commands.yaml#L22

I'll put up a fix shortly.

In the mean time, you should be able to swap out:
```
iam-list-saml-providers.json|.OpenIDConnectProviderList[]|.Arn
```
for
```
iam-list-saml-providers.json|..SAMLProviderList[]|.Arn
```

**Comment by tommy-bee** [comment]
I replaced
```
diff --git a/collect_commands.yaml b/collect_commands.yaml
index 941b3d7..a33937b 100644
--- a/collect_commands.yaml
+++ b/collect_commands.yaml
@@ -19,14 +19,14 @@
   Request: get-saml-provider
   Parameters:
   - Name: SamlProviderArn
-    Value: iam-list-saml-providers.json|.OpenIDConnectProviderList[]|.Arn
+    Value: iam-list-saml-providers.json|.SAMLProviderList[]|.Arn
 - Service: iam
   Request: list-open-id-connect-providers
 - Service: iam
   Request: get-open-id-connect-providers
   Parameters:
   - Name: SamlProviderArn
-    Value: iam-list-open-id-connect-providers.json|.SAMLProviderList[]|.Arn
+    Value: iam-list-saml-providers.json|.SAMLProviderList[]|.Arn
 - Service: s3
   Request: list-buckets
 - Service: s3
```

It got a lot further in the processing but eventually hit the same error message on sqs list:

```
Making call for account-data/./my_account/us-west-2/sqs-list-queues.json
* Getting sqs:get-queue-attributes info
Traceback (most recent call last):
  File "cloudmapper.py", line 69, in <module>
    main()
  File "cloudmapper.py", line 64, in main
    commands[command].run(arguments)
  File "/Users/tommy/src/aws/cloudmapper/commands/collect.py", line 221, in run
    collect(args)
  File "/Users/tommy/src/aws/cloudmapper/commands/collect.py", line 183, in collect
    values = pyjq.all(pyjq_parse_string or "", parameter_values)
  File "/Users/tommy/src/aws/cloudmapper/venv/lib/python3.7/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)
(venv)
```

**Comment by 0xdabbad00** [comment]
The first issue should now be resolved in #167.  I'm at a loss of what the cause of this new issue for you is though.  Try looking at `account-data/./my_account/us-west-2/sqs-list-queues.json`   The contents of that file should be `{}` or `{"QueueUrls":[]"}`

**Comment by tommy-bee** [comment]
It was `{}` in `account-data/./my_account/us-west-2/sqs-list-queues.json`

**Comment by FantailIO** [comment]
Same thing was required on: 

line 126: Value: cloudsearch-describe-domains.json|.DomainStatusList[]?|.DomainName
line 206: Value: glacier-list-vaults.json|.VaultList[]?|.VaultName

Seems like some of the AWS commands return 

{
  "Value": []
} 

and some return 

{}

The empty return upsets the array parsing in pyjq.

**Comment by sq-brootz** [comment]
Still getting this error with a new clone of the repo but in the prepare instead of collect.


Traceback (most recent call last):
  File "cloudmapper.py", line 69, in <module>
    main()
  File "cloudmapper.py", line 64, in main
    commands[command].run(arguments)
  File "/Users/ehansen/projects/cloudmapper/commands/prepare.py", line 419, in run
    prepare(account, config, outputfilter)
  File "/Users/ehansen/projects/cloudmapper/commands/prepare.py", line 345, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/Users/ehansen/projects/cloudmapper/commands/prepare.py", line 306, in build_data_structure
    for c, reasons in get_connections(cidrs, vpc, outputfilter).items():
  File "/Users/ehansen/projects/cloudmapper/commands/prepare.py", line 145, in get_connections
    for sg in instance.security_groups():
  File "/Users/ehansen/projects/cloudmapper/shared/nodes.py", line 320, in security_groups
    return pyjq.all('.SecurityGroups[]', self._json_blob)
  File "/usr/local/lib/python3.7/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)

Do you want this here or moved to a new issue?

**Comment by j4v** [comment]
Still getting this (latest master version):
```
$ python cloudmapper.py prepare --config xxx.json 
Building data for account xxx (xxx)
- 0 nodes built in region ap-south-1
- 0 nodes built in region eu-west-3
- 0 nodes built in region eu-west-2
- 0 nodes built in region eu-west-1
- 0 nodes built in region ap-northeast-2
- 0 nodes built in region ap-northeast-1
- 0 nodes built in region sa-east-1
- 0 nodes built in region ca-central-1
- 0 nodes built in region ap-southeast-1
- 0 nodes built in region ap-southeast-2
- 0 nodes built in region eu-central-1
- 0 nodes built in region us-east-1
- 0 nodes built in region us-east-2
- 0 nodes built in region us-west-1
Traceback (most recent call last):
  File "cloudmapper.py", line 69, in <module>
    main()
  File "cloudmapper.py", line 64, in main
    commands[command].run(arguments)
  File "/Git/cloudmapper/commands/prepare.py", line 419, in run
    prepare(account, config, outputfilter)
  File "/Git/cloudmapper/commands/prepare.py", line 345, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/Git/cloudmapper/commands/prepare.py", line 240, in build_data_structure
    outputfilter["collapse_asgs"])
  File "/Git/cloudmapper/shared/nodes.py", line 286, in __init__
    autoscaling_name = pyjq.all('.Tags[] | select(.Key == "aws:autoscaling:groupName") | .Value', json_blob)
  File "/Git/cloudmapper/venv/lib/python3.6/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)
```

**Comment by ntman4real** [comment]
same here, latest version

`(cloudmapper) bash-4.2# python cloudmapper.py prepare --config mgmtsvc.json --account mgmtsvc
Building data for account mgmtsvc (920886623150)
Traceback (most recent call last):
  File "cloudmapper.py", line 69, in <module>
    main()
  File "cloudmapper.py", line 64, in main
    commands[command].run(arguments)
  File "/cloudmapper/commands/prepare.py", line 419, in run
    prepare(account, config, outputfilter)
  File "/cloudmapper/commands/prepare.py", line 345, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/cloudmapper/commands/prepare.py", line 215, in build_data_structure
    for region_json in get_regions(account, outputfilter):
  File "/cloudmapper/shared/common.py", line 127, in get_regions
    regions = pyjq.all('.Regions[]{}'.format(region_filter), region_data)
  File "/root/.local/share/virtualenvs/cloudmapper-XcslQuzR/lib/python3.7/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)`

**Comment by ntman4real** [comment]
same here, latest version

`(cloudmapper) bash-4.2# python cloudmapper.py prepare --config mgmtsvc.json --account mgmtsvc
Building data for account mgmtsvc (XXXXXXXXX)
Traceback (most recent call last):
  File "cloudmapper.py", line 69, in <module>
    main()
  File "cloudmapper.py", line 64, in main
    commands[command].run(arguments)
  File "/cloudmapper/commands/prepare.py", line 419, in run
    prepare(account, config, outputfilter)
  File "/cloudmapper/commands/prepare.py", line 345, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/cloudmapper/commands/prepare.py", line 215, in build_data_structure
    for region_json in get_regions(account, outputfilter):
  File "/cloudmapper/shared/common.py", line 127, in get_regions
    regions = pyjq.all('.Regions[]{}'.format(region_filter), region_data)
  File "/root/.local/share/virtualenvs/cloudmapper-XcslQuzR/lib/python3.7/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)`

**Comment by tntlt** [comment]
The same for me:

ernis@ubuntu:~/cloudmapper$ sudo python3 cloudmapper.py prepare --account xxxxx --regions us-east-1                               
Building data for account xxxxxx (xxxxxx)
- 7 nodes built in region us-east-1
Traceback (most recent call last):
  File "cloudmapper.py", line 70, in <module>
    main()
  File "cloudmapper.py", line 65, in main
    commands[command].run(arguments)
  File "/home/ernis/cloudmapper/commands/prepare.py", line 419, in run
    prepare(account, config, outputfilter)
  File "/home/ernis/cloudmapper/commands/prepare.py", line 345, in prepare
    cytoscape_json = build_data_structure(account, config, outputfilter)
  File "/home/ernis/cloudmapper/commands/prepare.py", line 306, in build_data_structure
    for c, reasons in get_connections(cidrs, vpc, outputfilter).items():
  File "/home/ernis/cloudmapper/commands/prepare.py", line 145, in get_connections
    for sg in instance.security_groups():
  File "/home/ernis/cloudmapper/shared/nodes.py", line 320, in security_groups
    return pyjq.all('.SecurityGroups[]', self._json_blob)
  File "/usr/local/lib/python3.5/dist-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)
